# Generated by Django 2.2.3 on 2019-07-12 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20190711_1518'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='file',
            name='image',
        ),
        migrations.AlterField(
            model_name='folder',
            name='name',
            field=models.CharField(max_length=128, verbose_name='Название папки'),
        ),
    ]
